version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: vercel-railway-postgres
    environment:
      POSTGRES_DB: ecommerce_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application
  app:
    build: .
    container_name: vercel-railway-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/ecommerce_demo
      NODE_ENV: production
      PLATFORM: docker-local
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./public:/app/public
    restart: unless-stopped

volumes:
  postgres_data:
